language: csharp
solution: MyGame.sln
install:
  - nuget restore ExampleApplication.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - sudo apt-get install mono-complete
script:
  - msbuild ExampleApplication.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExampleApplication/bin/Debug/ExampleApplication.exe

